### ISSUE TITLE
Crash when printing help under Windows + MSYS2 mingw

### ISSUE THREAD

**Issue by kracejic** [Fytch/ProgramOptions.hxx#1]
When I try to print help for my test application in **MSYS2 bash, it crashes**:
```
Usage:
  websocketserver.exe [options]
Available options:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: D:\msys64\home\user\cpp\tools\websocketppExample\build\dist\bin\websocketserver.exe
File: ../external/ProgramOptions/src/ProgramOptions/ProgramOptions.hxx, Line 103
```
It **works as it should** in windows commandline.

Code to reproduce:
```
int main(int argc, char** argv)
{
    po::parser parser;
    parser["help"]
        .abbreviation('?')
        .description("print this help screen")
        .callback([&] { std::cout << parser << '\n'; });
    parser(argc, argv);
    if (parser["help"].size())
        return 0;
}
```

How I have "fixed" it (ProgramOptions.hxx: line ~104):
```
#ifdef PROGRAMOPTIONS_WINDOWS
			m_stream << std::flush;
			m_console = GetStdHandle( STD_OUTPUT_HANDLE );
			assert( m_console != INVALID_HANDLE_VALUE );
			CONSOLE_SCREEN_BUFFER_INFO info;
			const bool result = GetConsoleScreenBufferInfo( m_console, &info );
			//assert( result ); //<<<<< COMMENT THIS LINE :)
			( void )result;
			m_old_attributes = info.wAttributes;
			WORD attribute = 0;
			if( color < 0 ) {
```

After that, it works as it should. Is the check for result from GetCOnsoleScreenBufferInpfo necessary?

**Comment by Fytch** [comment]
I was not able to reproduce your problem. My GCC version is 6.3.0 and I tried both MSYS2 MinGW32 as well as MSYS2 MinGW64. Can you please specify your compiler version and the flags you've used for compilation? Do you see colored output when you comment out that line?

As to the result: No, it is theoretically not necessary to check whether the result was good or not but it should be true anyway, otherwise something went wrong. You may check what exactly went wrong by calling [GetLastError](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679360) and then compare the code with [this table](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681381). Seems like a problem with your MSYS2 or something.

I'm going to commit a change soon so that you are able to disable the WinAPI and rely on ANSI codes for colors in MSYS2 by manually defining a macro. But this should only be a temporary solution because the problem is probably in your MSYS2.

**Comment by kracejic** [comment]
GetLastError() gives me 6 - ERROR_INVALID_HANDLE
g++ version is 6.3.0 MinGW32
And all this is running under Windows 7 Enterprise.

```
$ cat sample.cxx
#include <ProgramOptions.hxx>
#include <iostream>

int main(int argc, char** argv)
{
    po::parser parser;
    parser["help"]
        .abbreviation('?')
        .description("print this help screen")
        .callback([&] { std::cout << parser << '\n'; });

    if (!parser(argc, argv))
    {
        return 1;
    }

    return 0;
}
$ g++ sample.cxx -I.
$ ./a.exe --help
Usage:
  a.exe [options]
Available options:
  GetLastError(): 6

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: ...websocketppExample\external\Progr
File: ./ProgramOptions.hxx, Line 105

Expression: result
$ echo $TERM
xterm-256color
$
```

I am running msys2 inside of mintty, just like you. Mintty version is 2.7.3 (x86_64-pc-msys). I have also tried to upgrade to newest version of all packages with the same result.

I have tested it with MINGW64 compiler and there it works without problem. It works when compiled with MINGW64, and executed in the MINGW32 console. 

It does not work when compiled with MINGW32 and executed in MING32 enviroment.
When trying to run MINGW32 executable in MINGW64 enviroment, I get error loading shared object. :)

**Comment by Fytch** [comment]
I'm sorry, I have no idea why the WinAPI doesn't work as it should in MinGW32. I came up with three workarounds for your problem:

1. [`#define PROGRAMOPTIONS_NO_COLORS`](https://github.com/Fytch/ProgramOptions.hxx#define-programoptions_no_colors) which disables all colored output on every platform.
2. [`#define PROGRAMOPTIONS_ANSI`](https://github.com/Fytch/ProgramOptions.hxx/commit/53f457406b00579eec55c6bdb648fc92bff313ce) which disables the usage of WinAPI but relies on ANSI escape codes for colored output. This works in all Unix-like shells, including mintty and Cygwin. However, it does not work in cmd.exe or Powershell because these two print the escape characters as though they were printable characters.
3. Just comment out the assertions in your local copy. (not recommended)

I suggest solution 2. I think the cleanest solution is to add something like this:
```cpp
#if defined( __MINGW32__ ) || defined( __CYGWIN__ )
    #define PROGRAMOPTIONS_ANSI
#endif
#include <ProgramOptions.hxx>
```
This way, ProgramOptions.hxx doesn't use WinAPI when compiling with MinGW or Cygwin but uses it when compiling with Visual Studio or ICC.

**Comment by kracejic** [comment]
Ok, thank you. 

Also a note in case somebody might stumble over this issue: In release mode it will work just fine (*-DNDEBUG* disables asserts).
