### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by Faykarta** [Fytch/ProgramOptions.hxx#10]
A few undesirable warnings firing. Easy enough to fixup.

ProgramOptions.h(1684): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
ProgramOptions.h(1686): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
ProgramOptions.h(2037): warning C4456: declaration of 'i' hides previous local declaration
ProgramOptions.h(644): warning C4456: declaration of 'neg' hides previous local declaration

**Comment by Faykarta** [comment]
another one - 
ProgramOptions.h(1521): warning C4127: conditional expression is constant
consider static_assert?

**Comment by Fytch** [comment]
Thanks for the feedback!

Do you use a modified version of ProgramOptions.hxx? Because the line numbers don't match up: https://github.com/Fytch/ProgramOptions.hxx/blob/master/ProgramOptions.hxx#L1684
https://github.com/Fytch/ProgramOptions.hxx/blob/master/ProgramOptions.hxx#L2037

Also, which flags and compiler do you use?

**Comment by Fytch** [comment]
Fixed in

https://github.com/Fytch/ProgramOptions.hxx/commit/bbf21c0592ddecf7f874f9973e1851d55496c6db

https://github.com/Fytch/ProgramOptions.hxx/commit/ea19c7197070db811982c2a991b9be8336b0d909

https://github.com/Fytch/ProgramOptions.hxx/commit/850d4d6d9671d83e622e38c7f18a85e2f77a121c
